{% set name = "darknet" %}
{% set version = "0.0.20200615" %}
{% set git_rev = "e08a818" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.g{{ git_rev }}

source:
  # NOTE: According to PJReddie, AlexeyAB's is the canonical version of darknet
  #       c.f.: https://twitter.com/pjreddie/status/1253891078182199296
  # NOTE: Upstream *does not* tag the repo
  git_url: https://github.com/AlexeyAB/darknet
  git_rev: {{ git_rev }}
  # NOTE: Upstream repo is very large.
  #       If build fails to pull the correct revision, increase the git-depth
  git_depth: 1
  patches:
    -  0001-Accept-a-different-toolchain.patch

build:
  number: 1
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgomp  # [linux]
{% if cuda_compiler_version != "None" %}
    - {{ compiler('cuda') }}
  host:
    - cudnn
  run_constrained:
    - __cuda {{ cuda_compiler_version }}
  run:
    - _darknet_mutex * gpu
{% else %}
  run:
    - _darknet_mutex * cpu
{% endif %}

test:
  commands:
    - test -x $PREFIX/bin/darknet
    - test -f $PREFIX/include/darknet.h
    - test -f $PREFIX/lib/libdarknet.so
      # - test -f $PREFIX/lib/libdarknet.a
    - darknet

outputs:
  - name: {{ name|lower }}
    files:
      - bin/darknet
      - include/darknet.h
      - lib/libdarknet.so
        # - lib/libdarknet.a

  - name: {{ name|lower }}-gpu  # [cuda_compiler_version != "None"]
  - name: {{ name|lower }}-cpu  # [cuda_compiler_version == "None"]
    requirements:
      run:
        - {{ pin_subpackage(name, exact=true) }}

about:
  home: https://pjreddie.com/darknet
  license: LicenseRef-darknet-public-domain
  license_file: LICENSE
  summary: Darknet is an open source neural network framework written in C and CUDA.

  dev_url: https://github.com/AlexeyAB/darknet

extra:
  recipe-maintainers:
    - sodre
